# Generated by Django 2.1.1 on 2018-09-25 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee', models.FloatField(default=0.1355)),
                ('price', models.FloatField(default=19.99)),
                ('total_accents', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='plays.Attendee')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='plays.Play')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('attendee', 'play')},
        ),
    ]
